# Generated by Django 3.1.2 on 2020-10-17 16:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, unique=True, verbose_name='Numero de Unidad')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de Unidad')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='UnityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('unity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unities.unity', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Contenido de la Unidad',
                'verbose_name_plural': 'Contenidos de la Unidad',
                'ordering': ['-title'],
            },
        ),
    ]
