# Generated by Django 3.1.2 on 2020-10-17 06:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido de la Unidad',
                'verbose_name_plural': 'Contenidos de la Unidad',
                'ordering': ['-title'],
            },
        ),
    ]
