# Generated by Django 3.1.2 on 2020-10-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0002_unitycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitycontent',
            name='unity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unities.unity', verbose_name='Unidad'),
        ),
    ]
