# Generated by Django 3.1.2 on 2020-10-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0002_auto_20201019_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitycontent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
