# Generated by Django 3.1.2 on 2020-10-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0003_unitycontent_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='unity',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Numero de Unidad'),
        ),
        migrations.AlterField(
            model_name='unity',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
