# Generated by Django 3.1.2 on 2020-10-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0003_unitycontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitycontent',
            name='header_img',
            field=models.ImageField(upload_to='header-img', verbose_name='Imagen en encabezado'),
        ),
    ]
