# Generated by Django 3.1.2 on 2020-10-24 19:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0004_auto_20201022_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitycontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
