# Generated by Django 3.1.2 on 2020-10-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0004_auto_20201017_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unity',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
