# Generated by Django 3.1.2 on 2020-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0005_auto_20201017_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitycontent',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
