# Generated by Django 3.1.2 on 2020-10-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unities', '0006_auto_20201017_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unity',
            options={'ordering': ['-number'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='unity',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
