# Generated by Django 3.1.2 on 2020-10-18 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10, unique=True, verbose_name='Boleta')),
                ('profile_img', models.ImageField(upload_to='profile-img', verbose_name='Foto de Perfil')),
                ('role', models.CharField(max_length=30, verbose_name='Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Equipo',
                'verbose_name_plural': 'Miembros de Equipo',
                'ordering': ['-user'],
            },
        ),
    ]
