# Generated by Django 3.1.2 on 2021-04-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210424_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, default='No ha dado descripcion', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(default='Cargo no Asignado', max_length=30, verbose_name='Cargo'),
        ),
    ]
