# Generated by Django 3.1.2 on 2020-10-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201016_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-surname'], 'verbose_name': 'Miembro de Equipo', 'verbose_name_plural': 'Miembros de Equipo'},
        ),
    ]
