# Generated by Django 3.1.2 on 2021-05-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_teammember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsoftDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento de Prosoft',
                'verbose_name_plural': 'Documentos de Prosoft',
                'ordering': ['-created', 'title'],
            },
        ),
    ]
