# Generated by Django 3.1.2 on 2021-05-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prosoftdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProsoftDoc',
        ),
    ]
