# Generated by Django 3.1.2 on 2021-05-24 17:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prosoftdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosoftdoc',
            name='document',
            field=models.FileField(upload_to='prosoft/', validators=[core.validators.validate_file_extension]),
        ),
    ]
