# Generated by Django 3.1.2 on 2021-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210524_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosoftdoc',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
