# Generated by Django 3.1.2 on 2021-06-02 23:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210524_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='market_rate/', validators=[core.validators.validate_file_extension])),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
    ]
