# Generated by Django 3.1.2 on 2021-06-05 19:11

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210603_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketrate',
            options={},
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='document',
            field=models.FileField(blank=True, upload_to='market_rate/', validators=[core.validators.validate_file_extension], verbose_name='Documento'),
        ),
    ]
