# Generated by Django 3.1.2 on 2021-06-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210605_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketrate',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
