# Generated by Django 3.1.2 on 2021-06-07 21:53

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210605_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitucionalAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to='market_rate/', validators=[core.validators.validate_file_extension], verbose_name='Documento')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acta Constitucional',
                'verbose_name_plural': 'Actas Constitucional',
            },
        ),
    ]
