# Generated by Django 3.1.2 on 2021-06-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_constitucionalact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitucionalact',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
