# Generated by Django 3.1.2 on 2021-06-23 20:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to='venta/', validators=[core.validators.validate_file_extension], verbose_name='Documento')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Venta al Gobierno',
                'verbose_name_plural': 'Ventas al Gobierno',
            },
        ),
    ]
